config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }

  root 'videos#index'

  resources :videos, except: %i[show edit update destroy]
  resources :users, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :videos, dependent: :destroy

  validates :email, presence: true
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

  validates :url, presence: true

  def youtube_embed_url
    code = url.split('v=').last
    "https://youtube.com/embed/#{code}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.find_by_email(email)

    if user
      if user.valid_password?(password)
        sign_in_with!(user)
      else
        flash[:error] = 'Invalid password'
      end
    else
      user = User.new(user_params)
      if user.save
        sign_in_with!(user)
      else
        flash[:error] = 'Sorry we cannot process your request at the moment'
      end
    end

    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end

    def email
      params[:user][:email]
    end

    def password
      params[:user][:password]
    end

    def sign_in_with!(user)
      sign_in(user)
      flash[:notice] = 'Logged in successfully'
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, except: :index

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/new
  def new
    @video = current_user.videos.new
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = current_user.videos.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_path, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        flash[:error] = @video.errors.full_messages.join(', ')
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_video
      @video = current_user.videos.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:user_id, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header
    if user_signed_in?
      render 'layouts/auth_info'
    else
      render 'layouts/auth_form'
    end
  end
end

app/views/layouts/_auth_form.html.slim
= form_for(User.new) do |f|
  = f.text_field :email
  = f.password_field :password
  = f.submit 'Login / Register'

app/views/layouts/_auth_info.html.slim
.inline Welcome #{current_user.email}
.inline
  = link_to 'Share a movie', new_video_path
  = link_to('Logout', destroy_user_session_path, method: :delete)

app/views/layouts/_header.html.slim
.header
  .app-name Funny Videos
  .pull-right
    = header
  .clearfix
.flash-notice
  - if flash[:notice]
    .green-notice = flash[:notice]
  - if flash[:error]
    .red-notice = flash[:error]

app/views/layouts/application.html.slim
doctype html
html
  head
    title FunnyVideos
    = csrf_meta_tags
    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    = yield

app/views/videos/_form.html.slim
= form_for @video do |f|
  .field
    = f.label :url, 'Youtube URL', class: 'field-label'
    = f.text_field :url, class: 'field'
  .actions.text-center
    = f.submit 'Share Video'

app/views/videos/edit.html.slim
h1 Editing video

== render 'form'

=> link_to 'Show', @video
'|
=< link_to 'Back', videos_path

app/views/videos/index.html.slim
.mx-auto.m-t-lg
  table
    - @videos.each do |video|
      tr
        td
          iframe src=video.youtube_embed_url height="200" width="350"
        td
          div Shared by #{video.user&.email}

app/views/videos/new.html.slim
.mx-auto.b-a.p-a-md.m-t-lg
  = render 'form'

app/views/videos/show.html.slim
p#notice = notice

p
  strong User:
  = @video.user_id
p
  strong Url:
  = @video.url

=> link_to 'Edit', edit_video_path(@video)
'|
=< link_to 'Back', videos_path